/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type { IPostgresInterval } from "postgres-interval";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Interval = ColumnType<IPostgresInterval, IPostgresInterval | number | string, IPostgresInterval | number | string>;

export type JsonPrimitive = boolean | number | string;

export type JsonValue = JsonPrimitive | JsonObject | JsonArray | null;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type Json = Exclude<JsonValue, null>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Point = {
  x: number;
  y: number;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessToken {
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  user_type: string;
}

export interface AccessTokenType {
  type: string;
}

export interface AccountSubscriptionStatus {
  sms_credit_top_up_at: Timestamp | null;
  sms_credit_top_up_count: number | null;
  subscription: Json | null;
  trainer_id: string | null;
}

export interface AnalyticsData {
  anonymous_id: string | null;
  context_active: boolean | null;
  context_app_build: string | null;
  context_app_name: string | null;
  context_app_namespace: string | null;
  context_app_version: string | null;
  context_campaign_content: string | null;
  context_campaign_medium: string | null;
  context_campaign_name: string | null;
  context_campaign_source: string | null;
  context_campaign_term: string | null;
  context_device_ad_tracking_enabled: string | null;
  context_device_advertising_id: string | null;
  context_device_id: string | null;
  context_device_manufacturer: string | null;
  context_device_model: string | null;
  context_device_name: string | null;
  context_device_type: string | null;
  context_device_version: string | null;
  context_group_id: string | null;
  context_ip: string | null;
  context_library_name: string | null;
  context_library_version: string | null;
  context_locale: string | null;
  context_location_city: string | null;
  context_location_country: string | null;
  context_location_latitude: number | null;
  context_location_longitude: number | null;
  context_location_region: string | null;
  context_location_speed: number | null;
  context_network_bluetooth: boolean | null;
  context_network_carrier: string | null;
  context_network_cellular: boolean | null;
  context_network_wifi: boolean | null;
  context_os_name: string | null;
  context_os_version: string | null;
  context_page_hash: string | null;
  context_page_path: string | null;
  context_page_referrer: string | null;
  context_page_search: string | null;
  context_page_title: string | null;
  context_page_url: string | null;
  context_referrer_id: string | null;
  context_referrer_link: string | null;
  context_referrer_name: string | null;
  context_referrer_type: string | null;
  context_referrer_url: string | null;
  context_screen_density: number | null;
  context_screen_height: number | null;
  context_screen_width: number | null;
  context_timezone: string | null;
  context_user_agent: string | null;
  event: string | null;
  id: Generated<string>;
  properties: Json | null;
  received_at: Timestamp;
  screen: string | null;
  timestamp: Timestamp;
  type: string | null;
  user_id: string | null;
}

export interface AppleSearchAdsAttribution {
  adgroup_id: string | null;
  adgroup_name: string | null;
  anonymous_id: string;
  attribution: boolean | null;
  campaign_id: string | null;
  campaign_name: string | null;
  click_date: Timestamp | null;
  conversion_date: Timestamp | null;
  conversion_type: string | null;
  country_or_region: string | null;
  creativeset_id: string | null;
  creativeset_name: string | null;
  id: Generated<string>;
  keyword: string | null;
  keyword_id: string | null;
  keyword_matchtype: string | null;
  org_id: string | null;
  org_name: string | null;
  purchase_date: Timestamp | null;
}

export interface AppNotification {
  body: string;
  client_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  message_type: string;
  notification_type: string;
  payment_id: string | null;
  payment_plan_id: string | null;
  payment_plan_payment_id: string | null;
  session_pack_id: string | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  user_type: Generated<string>;
  viewed: Generated<boolean>;
}

export interface AppStorePendingRenewalInfo {
  created_at: Generated<Timestamp>;
  data: Json;
  product_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AppStoreServerNotification {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  object: Json;
  receive_time: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface AppStoreTransaction {
  created_at: Generated<Timestamp>;
  encoded_receipt: string;
  expires_date: Timestamp;
  is_in_intro_offer_period: boolean;
  is_trial_period: boolean;
  original_transaction_id: string;
  product_id: string;
  purchase_date: Timestamp;
  trainer_id: string;
  transaction_id: string;
  updated_at: Generated<Timestamp>;
  web_order_line_item_id: string;
}

export interface Availability {
  accepting_bookings: boolean | null;
  available_intervals: string[] | null;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface BalanceTransactions {
  amount: Numeric;
  currency: string;
  id: string;
  transaction_time: Timestamp;
}

export interface BookingPaymentType {
  type: string;
}

export interface BookingQuestionState {
  state: string;
}

export interface BrandColor {
  id: string;
}

export interface BusyTime {
  created_at: Generated<Timestamp>;
  end_date: Timestamp | null;
  end_time: Timestamp | null;
  id: Generated<string>;
  start_date: Timestamp | null;
  start_time: Timestamp | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Client {
  address: string | null;
  birthday: Timestamp | null;
  company: string | null;
  created_at: Generated<Timestamp>;
  current_injuries: string | null;
  email: string | null;
  email_appointment_reminders_enabled: Generated<boolean>;
  emergency_contact_mobile_number: string | null;
  emergency_contact_name: string | null;
  first_name: string;
  geo: Point | null;
  goals: string | null;
  google_place_id: string | null;
  id: Generated<string>;
  last_name: string | null;
  location: string | null;
  medication: string | null;
  mobile_number: string | null;
  notes: string | null;
  other_number: string | null;
  password_hash: string | null;
  past_injuries: string | null;
  profile_image_url: string | null;
  sms_reminders_enabled: Generated<boolean>;
  status: string;
  stripe_customer_id: string | null;
  terms_accepted: Generated<boolean>;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  user_type: Generated<string>;
}

export interface ClientAppointmentReminderType {
  type: string;
}

export interface ClientLoginRequest {
  authenticated: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Generated<Timestamp>;
  failed_authentication_count: Generated<number>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ClientNote {
  body: string | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  title: string | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClientPaymentReminder {
  client_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  send_success: boolean;
  send_time: Generated<Timestamp | null>;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClientSession {
  accept_time: Timestamp | null;
  booked_online: Generated<boolean | null>;
  booking_icalendar_url: string | null;
  booking_id: Generated<string | null>;
  booking_question: string | null;
  booking_question_response: string | null;
  cancel_reason: string | null;
  cancel_time: Timestamp | null;
  client_id: string;
  confirm_time: Timestamp | null;
  created_at: Generated<Timestamp>;
  decline_time: Timestamp | null;
  id: Generated<string>;
  invite_time: Timestamp | null;
  note: string | null;
  price: Numeric | null;
  sale_id: string | null;
  session_id: string;
  state: Generated<string>;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClientSessionState {
  state: string;
}

export interface ClientStatus {
  status: string;
}

export interface Country {
  alpha_2_code: string;
  alpha_3_code: string;
  id: number;
  name: string;
}

export interface CreditPack {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_credit_pack: Generated<boolean>;
  total_credits: number;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Currency {
  alpha_code: string;
  id: number;
  name: string;
}

export interface EmailAppointmentReminder {
  client_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_client_reminder: Generated<boolean>;
  mail_id: string;
  session_id: string | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface EventType {
  type: string;
}

export interface FinanceItem {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  image_url: string | null;
  name: string;
  note: string | null;
  start_date: Timestamp;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Installation {
  created_at: Generated<Timestamp>;
  device_token: string;
  device_type: string;
  id: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  user_type: Generated<string>;
}

export interface LoggedActions {
  /**
   * Action type; I = insert, D = delete, U = update, T = truncate
   */
  action: string;
  /**
   * Wall clock time at which audited event's trigger call occurred
   */
  action_tstamp_clk: Timestamp;
  /**
   * Statement start timestamp for tx in which audited event occurred
   */
  action_tstamp_stm: Timestamp;
  /**
   * Transaction start timestamp for tx in which audited event occurred
   */
  action_tstamp_tx: Timestamp;
  /**
   * Application name set when this audit event occurred. Can be changed in-session by client.
   */
  application_name: string | null;
  /**
   * New values of fields changed by UPDATE. Null except for row-level UPDATE events.
   */
  changed_fields: string | null;
  /**
   * IP address of client that issued query. Null for unix domain socket.
   */
  client_addr: string | null;
  /**
   * Remote peer IP port address of client that issued query. Undefined for unix socket.
   */
  client_port: number | null;
  /**
   * Top-level query that caused this auditable event. May be more than one statement.
   */
  client_query: string | null;
  /**
   * Unique identifier for each auditable event
   */
  event_id: Generated<Int8>;
  /**
   * Table OID. Changes with drop/create. Get with 'tablename'::regclass
   */
  relid: number;
  /**
   * Record value. Null for statement-level trigger. For INSERT this is the new tuple. For DELETE and UPDATE it is the old tuple.
   */
  row_data: string | null;
  /**
   * Database schema audited table for this event is in
   */
  schema_name: string;
  /**
   * Login / session user whose statement caused the audited event
   */
  session_user_name: string | null;
  /**
   * 't' if audit event is from an FOR EACH STATEMENT trigger, 'f' for FOR EACH ROW
   */
  statement_only: boolean;
  /**
   * Non-schema-qualified table name of table event occured in
   */
  table_name: string;
  /**
   * Identifier of transaction that made the change. May wrap, but unique paired with action_tstamp_tx.
   */
  transaction_id: Int8 | null;
}

export interface Mail {
  client_id: string | null;
  client_was_deleted: boolean | null;
  created_at: Generated<Timestamp>;
  from_email: string;
  from_name: string | null;
  html: string;
  id: Generated<string>;
  mandrill_message_id: string | null;
  queued_at: Timestamp | null;
  reject_reason: string | null;
  rejected_at: Timestamp | null;
  reply_to: string | null;
  sent_at: Timestamp | null;
  subject: string;
  to_email: string;
  to_name: string | null;
  trainer_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MailBounce {
  bounce_type: string | null;
  bounced_at: Timestamp;
  created_at: Generated<Timestamp>;
  description: string | null;
  diagnosis: string | null;
  id: Generated<string>;
  mail_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MailBounceType {
  type: string;
}

export interface MailClick {
  clicked_at: Timestamp;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip: string;
  location: Json | null;
  mail_id: string;
  updated_at: Generated<Timestamp>;
  url: string;
  user_agent: string;
}

export interface MailOpen {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip: string;
  location: Json | null;
  mail_id: string;
  opened_at: Timestamp;
  updated_at: Generated<Timestamp>;
  user_agent: string;
}

export interface MandrillEvent {
  _id: string;
  created_at: Generated<Timestamp>;
  event: string;
  object: Json;
  processed_at: Timestamp | null;
  ts: Int8;
  updated_at: Generated<Timestamp>;
}

export interface Message {
  created_at: Generated<Timestamp>;
  object: Json;
  sid: string;
  updated_at: Generated<Timestamp>;
}

export interface Metrics {
  apple_sales: Generated<Numeric | null>;
  date: Timestamp;
  discounted_arpa: number | null;
  discounted_churn_estimate: number | null;
  discounted_churned_mmr_amount: Generated<Numeric | null>;
  discounted_churned_sub_count: Generated<number | null>;
  discounted_new_mmr_amount: Generated<Numeric | null>;
  discounted_new_sub_count: Generated<number | null>;
  discounted_reactivated_mmr_amount: Generated<Numeric | null>;
  discounted_reactivated_sub_count: Generated<number | null>;
  impression_count: Generated<number | null>;
  install_count: Generated<number | null>;
  new_account_count: Generated<number | null>;
  page_view_count: Generated<number | null>;
  standard_arpa: number | null;
  standard_churn_estimate: number | null;
  standard_churned_mmr_amount: Generated<Numeric | null>;
  standard_churned_sub_count: Generated<number | null>;
  standard_new_mmr_amount: Generated<Numeric | null>;
  standard_new_sub_count: Generated<number | null>;
  standard_reactivated_mmr_amount: Generated<Numeric | null>;
  standard_reactivated_sub_count: Generated<number | null>;
  unique_impression_count: Generated<number | null>;
  unique_page_view_count: Generated<number | null>;
}

export interface Mission {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  display_order: number;
  id: string;
  reward_id: string | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MissionType {
  action_url: string | null;
  description: string;
  id: string;
  title: string;
}

export interface Mrr {
  churn_amount: Numeric | null;
  date: Timestamp | null;
  months_paid: number | null;
  new_amount: Numeric | null;
  reactivate_amount: Numeric | null;
}

export interface Payment {
  amount: Numeric;
  client_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_credit_pack: boolean | null;
  is_manual: boolean | null;
  is_scheduled_stripe: boolean | null;
  is_stripe: boolean | null;
  is_subscription: boolean | null;
  refunded_time: Timestamp | null;
  sale_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentCreditPack {
  created_at: Generated<Timestamp>;
  credits_used: number;
  id: Generated<string>;
  is_credit_pack: Generated<boolean>;
  sale_credit_pack_id: string;
  trainer_id: string;
  transaction_time: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface PaymentManual {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_manual: Generated<boolean>;
  method: string;
  specific_method_name: string | null;
  trainer_id: string;
  transaction_time: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface PaymentMethod {
  created_at: Generated<Timestamp>;
  method: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentPlan {
  acceptance_request_time: Timestamp | null;
  accepted_amount: Numeric | null;
  accepted_end: Timestamp | null;
  amount: Numeric;
  client_id: string;
  created_at: Generated<Timestamp>;
  end_: Timestamp;
  frequency_weekly_interval: number;
  id: Generated<string>;
  name: string;
  start: Timestamp;
  status: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentPlanAcceptance {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  end_: Timestamp;
  id: Generated<string>;
  ip_address: string;
  payment_plan_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentPlanCharge {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payment_plan_payment_id: string;
  stripe_charge_id: string | null;
  stripe_payment_intent_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PaymentPlanPause {
  created_at: Generated<Timestamp>;
  end_: Timestamp;
  id: Generated<string>;
  payment_plan_id: string;
  start: Timestamp;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentPlanPayment {
  amount: Numeric;
  amount_outstanding: Numeric;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  fee: Numeric | null;
  id: Generated<string>;
  last_retry_time: Timestamp | null;
  payment_plan_id: string;
  retry_count: Generated<number>;
  status: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentPlanPaymentStatus {
  created_at: Generated<Timestamp>;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentPlanStatus {
  status: string;
}

export interface PaymentScheduledStripe {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_scheduled_stripe: Generated<boolean>;
  stripe_charge_id: string | null;
  trainer_id: string;
  trigger_time: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface PaymentScheduledStripeAttempt {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payment_scheduled_stripe_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentStats {
  count: Int8 | null;
  max_date: Timestamp | null;
}

export interface PaymentStatus {
  status: string;
}

export interface PaymentStripe {
  created_at: Generated<Timestamp>;
  fee: Numeric;
  fee_passed_on: Generated<boolean>;
  id: Generated<string>;
  is_stripe: Generated<boolean>;
  stripe_charge_id: string | null;
  stripe_payment_intent_id: string | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentSubscription {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_subscription: Generated<boolean>;
  subscription_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  parallel_workers_launched: Int8 | null;
  parallel_workers_to_launch: Int8 | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_buffers_full: Int8 | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface PgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface Product {
  created_at: Generated<Timestamp>;
  currency_id: number;
  description: string;
  display_order: number | null;
  id: Generated<string>;
  is_credit_pack: boolean | null;
  is_item: boolean | null;
  is_membership: boolean | null;
  is_service: boolean | null;
  name: string;
  price: Numeric;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RequestClientAddressOnlineType {
  type: string;
}

export interface Reward {
  claimed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  trainer_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface RewardType {
  description: string;
  title: string;
  type: string;
}

export interface Sale {
  client_id: string;
  created_at: Generated<Timestamp>;
  due_time: Generated<Timestamp>;
  id: Generated<string>;
  note: Generated<string>;
  payment_request_pass_on_transaction_fee: Generated<boolean>;
  payment_request_time: Timestamp | null;
  subscription_period_id: string | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SaleCreditPack {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_credit_pack: Generated<boolean>;
  total_credits: number;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SaleItem {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_item: Generated<boolean>;
  quantity: Generated<number>;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SalePaymentStatus {
  payment_status: string | null;
  sale_id: string | null;
}

export interface SaleProduct {
  client_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_credit_pack: boolean | null;
  is_item: boolean | null;
  is_membership: boolean | null;
  is_service: boolean | null;
  name: string;
  price: Numeric;
  product_id: string | null;
  sale_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SaleService {
  address: string | null;
  created_at: Generated<Timestamp>;
  duration: Interval | null;
  geo: Point | null;
  google_place_id: string | null;
  id: Generated<string>;
  is_service: Generated<boolean>;
  location: string | null;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SchemaHistory {
  checksum: string | null;
  description: string;
  execution_time: number;
  installed_by: string | null;
  installed_on: Generated<Timestamp>;
  installed_rank: Generated<number>;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface SchemaMigrations {
  version: string;
}

export interface Service {
  address: string | null;
  bookable_online: boolean;
  booking_payment_type: Generated<string>;
  booking_question: string | null;
  booking_question_state: string | null;
  buffer_minutes_after: Generated<number>;
  buffer_minutes_before: Generated<number>;
  cover_image_url: string | null;
  created_at: Generated<Timestamp>;
  duration: Interval | null;
  geo: Point | null;
  google_place_id: string | null;
  icon_url: string | null;
  id: Generated<string>;
  image_0_url: string | null;
  image_1_url: string | null;
  image_2_url: string | null;
  image_3_url: string | null;
  image_4_url: string | null;
  image_5_url: string | null;
  is_service: Generated<boolean>;
  location: string | null;
  request_client_address_online: string | null;
  time_slot_frequency_minutes: Generated<number>;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ServiceProviderAppointmentReminderType {
  type: string;
}

export interface Session {
  address: string | null;
  bookable_online: Generated<boolean>;
  booked_online: Generated<boolean | null>;
  booking_payment_type: Generated<string>;
  booking_question: string | null;
  booking_question_state: string | null;
  buffer_minutes_after: Generated<number>;
  buffer_minutes_before: Generated<number>;
  can_clients_cancel: Generated<boolean>;
  cancellation_advance_notice_duration: Generated<Interval>;
  client_reminder_1: Interval | null;
  client_reminder_1_checked_at: Timestamp | null;
  client_reminder_1_type: Generated<string>;
  client_reminder_2: Interval | null;
  client_reminder_2_checked_at: Timestamp | null;
  client_reminder_2_type: Generated<string>;
  created_at: Generated<Timestamp>;
  description: string | null;
  duration: Interval;
  geo: Point | null;
  google_place_id: string | null;
  id: Generated<string>;
  location: string | null;
  maximum_attendance: number | null;
  note: string | null;
  request_client_address_online: string | null;
  service_id: string | null;
  service_provider_reminder_1: Interval | null;
  service_provider_reminder_1_checked_at: Timestamp | null;
  service_provider_reminder_1_type: Generated<string>;
  service_provider_reminder_2: Interval | null;
  service_provider_reminder_2_checked_at: Timestamp | null;
  service_provider_reminder_2_type: Generated<string>;
  session_series_id: string;
  sms_reminder_sent_time: Timestamp | null;
  start: Timestamp;
  timezone: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SessionIcon {
  id: string;
}

export interface SessionSeries {
  color: string | null;
  created_at: Generated<Timestamp>;
  daily_recurrence_interval: Interval | null;
  duration: Interval;
  end_: Timestamp | null;
  event_type: string;
  icon_url: string | null;
  id: Generated<string>;
  location: string | null;
  name: string | null;
  price: Numeric | null;
  session_icon_id: string | null;
  start: Timestamp;
  timezone: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Sms {
  body: string;
  client_id: string | null;
  client_was_deleted: boolean | null;
  created_at: Generated<Timestamp>;
  from_number: string | null;
  id: Generated<string>;
  queue_failed_at: Timestamp | null;
  queue_failed_reason: string | null;
  queued_at: Timestamp | null;
  to_number: string;
  trainer_id: string | null;
  twilio_message_sid: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SmsBalance {
  credit_balance: Int8 | null;
  trainer_id: string | null;
}

export interface SmsCredit {
  amount: number;
  created_at: Generated<Timestamp>;
  id: Generated<string | null>;
  sms_credit_checkout_session_id: string | null;
  source: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SmsCreditCheckoutSession {
  created_at: Generated<Timestamp>;
  credit_count: number;
  id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SmsCreditSource {
  source: string;
}

export interface StripeAccount {
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripeBalance {
  account_id: string;
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripeBankAccount {
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripeCharge {
  api_version: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json | null;
  updated_at: Generated<Timestamp>;
}

export interface StripeCheckoutSession {
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripeCustomer {
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripeEvent {
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  processed_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface StripeInvoice {
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripePaymentIntent {
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json | null;
  updated_at: Generated<Timestamp>;
}

export interface StripePaymentMethod {
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripePayout {
  account: string;
  api_version: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripeResource {
  api_version: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp>;
}

export interface StripeSubscription {
  api_version: Timestamp;
  created_at: Generated<Timestamp | null>;
  id: string;
  object: Json;
  updated_at: Generated<Timestamp | null>;
}

export interface Subscription {
  accept_time: Timestamp | null;
  amount: Numeric;
  client_id: string | null;
  created_at: Generated<Timestamp>;
  end_time: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  name: string;
  recurrence_frequency: string;
  recurrence_interval: number;
  start_time: Timestamp;
  timezone: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SubscriptionFrequency {
  duration: Interval;
  frequency: string;
}

export interface SubscriptionPause {
  client_id: string | null;
  created_at: Generated<Timestamp>;
  end_time: Timestamp;
  id: Generated<string>;
  start_time: Timestamp;
  subscription_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SubscriptionPeriod {
  client_id: string | null;
  created_at: Generated<Timestamp>;
  end_time: Timestamp;
  id: string;
  start_time: Timestamp;
  subscription_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SubscriptionUpdate {
  accept_time: Timestamp | null;
  amount: Numeric;
  client_id: string | null;
  created_at: Generated<Timestamp>;
  end_time: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  recurrence_frequency: string;
  recurrence_interval: number;
  subscription_id: string;
  timezone: string;
  trainer_id: string;
  update_time: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface SupportedCountryCurrency {
  country_id: number;
  currency_id: number;
}

export interface Survey {
  features: Generated<string[]>;
  id: Generated<number>;
  industry: string | null;
  survey_time: Generated<Timestamp>;
  topics_to_improve: Generated<string[]>;
  trainer_id: string;
  years_experience: string | null;
}

export interface Tableslist {
  auditedtable: string | null;
  schema: string | null;
}

export interface TaskQueue {
  attempt_deadline: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  data: Json | null;
  first_attempt_time: Timestamp | null;
  id: Generated<Int8>;
  last_attempt_time: Timestamp | null;
  max_attempts: Generated<number>;
  max_backoff: Generated<Interval>;
  max_doublings: Generated<number>;
  max_retry_duration: Interval | null;
  min_backoff: Generated<Interval>;
  recurring_schedule: string | null;
  retry_count: Generated<number>;
  schedule_time: Generated<Timestamp>;
  task_type: string;
  timezone: string | null;
}

export interface Trainer {
  admin_note: string | null;
  brand_color: Generated<string>;
  brand_dark_mode: Generated<boolean | null>;
  business_logo_url: string | null;
  business_name: string | null;
  country_id: number;
  cover_image_url: string | null;
  created_at: Generated<Timestamp>;
  default_can_clients_cancel_appointment: Generated<boolean>;
  default_cancellation_advance_notice_duration: Generated<Interval>;
  default_client_appointment_reminder_1: Interval | null;
  default_client_appointment_reminder_1_type: Generated<string>;
  default_client_appointment_reminder_2: Interval | null;
  default_client_appointment_reminder_2_type: Generated<string>;
  default_service_provider_appointment_reminder_1: Interval | null;
  default_service_provider_appointment_reminder_1_type: Generated<string>;
  default_service_provider_appointment_reminder_2: Interval | null;
  default_service_provider_appointment_reminder_2_type: Generated<string>;
  eligible_for_grandfather: Generated<boolean>;
  email: string;
  first_name: string;
  first_user_agent: string | null;
  icalendar_url_slug: Generated<string>;
  id: Generated<string>;
  industry: string | null;
  last_ios_id_for_vendor: string | null;
  last_name: string | null;
  last_wrap_date: Timestamp | null;
  locale: string;
  minimum_balance: Generated<Numeric>;
  monthly_price_override: Numeric | null;
  online_bookings_booking_note: string | null;
  online_bookings_business_name: string | null;
  online_bookings_cancellation_policy: string | null;
  online_bookings_contact_email: string | null;
  online_bookings_contact_number: string | null;
  online_bookings_duration_until_booking_window_closes: Generated<Interval>;
  online_bookings_duration_until_booking_window_opens: Generated<Interval>;
  online_bookings_enabled: Generated<boolean>;
  online_bookings_friday_accepting_bookings: Generated<boolean>;
  online_bookings_friday_available_intervals: Generated<string[]>;
  online_bookings_monday_accepting_bookings: Generated<boolean>;
  online_bookings_monday_available_intervals: Generated<string[]>;
  online_bookings_page_url_slug: Generated<string>;
  online_bookings_saturday_accepting_bookings: Generated<boolean>;
  online_bookings_saturday_available_intervals: Generated<string[]>;
  online_bookings_show_contact_number: Generated<boolean | null>;
  online_bookings_sunday_accepting_bookings: Generated<boolean>;
  online_bookings_sunday_available_intervals: Generated<string[]>;
  online_bookings_terms_and_conditions: string | null;
  online_bookings_thursday_accepting_bookings: Generated<boolean>;
  online_bookings_thursday_available_intervals: Generated<string[]>;
  online_bookings_tuesday_accepting_bookings: Generated<boolean>;
  online_bookings_tuesday_available_intervals: Generated<string[]>;
  online_bookings_wednesday_accepting_bookings: Generated<boolean>;
  online_bookings_wednesday_available_intervals: Generated<string[]>;
  partner: string | null;
  password_hash: string;
  phone_number: string | null;
  receive_wraps: Generated<boolean>;
  send_receipts: Generated<boolean>;
  sign_in_with_apple_user_id: string | null;
  sms_credit_checkout_id: Generated<string>;
  stripe_account_id: string | null;
  stripe_customer_id: string | null;
  stripe_payments_blocked: Generated<boolean | null>;
  stripe_subscription_id: string | null;
  terms_accepted: Generated<boolean>;
  timezone: string;
  trialled_didnt_sub_mailchimp_tag_applied: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  user_type: Generated<string>;
  yearly_price_override: Numeric | null;
}

export interface Trial {
  created_at: Generated<Timestamp>;
  end_time: Timestamp;
  id: Generated<string>;
  start_time: Generated<Timestamp>;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface User {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface UserType {
  type: string;
}

export interface VwFirstCardPayments {
  first_card_payment_processed: Timestamp | null;
  trainer_id: string | null;
}

export interface VwLegacyAppNotification {
  alert: string | null;
  category: string | null;
  client_id: string | null;
  created: Timestamp | null;
  expiration_interval: string | null;
  id: string | null;
  message_type: string | null;
  model_id: string | null;
  model_name: string | null;
  notification_type: string | null;
  user_id: string | null;
  viewed: boolean | null;
}

export interface VwLegacyClient {
  address: string | null;
  birthday: Timestamp | null;
  cardBrand: string | null;
  cardLast4Digits: string | null;
  company: string | null;
  email: string | null;
  emergencyContactMobileNumber: string | null;
  emergencyContactName: string | null;
  firstName: string | null;
  geo: Json | null;
  googlePlaceId: string | null;
  id: string | null;
  lastName: string | null;
  location: string | null;
  memberId: string | null;
  mobileNumber: string | null;
  notes: Json | null;
  otherNumber: string | null;
  plans: Json | null;
  profileImageURL: string | null;
  sessionPacks: Json | null;
  status: string | null;
  stripeCustomer: string | null;
  termsAccepted: boolean | null;
  trainerId: string | null;
}

export interface VwLegacyClientSession {
  acceptTime: Timestamp | null;
  attended: boolean | null;
  bookingQuestion: string | null;
  bookingQuestionResponse: string | null;
  cancelReason: string | null;
  cancelTime: Timestamp | null;
  clientId: string | null;
  confirmTime: Timestamp | null;
  createdAt: Timestamp | null;
  declineTime: Timestamp | null;
  id: string | null;
  inviteTime: Timestamp | null;
  notes: Json | null;
  payment: Json | null;
  price: number | null;
  saleId: string | null;
  sessionId: string | null;
  state: string | null;
}

export interface VwLegacyFinanceItem {
  amount: number | null;
  createdAt: Timestamp | null;
  id: string | null;
  imageUrl: string | null;
  name: string | null;
  paymentType: string | null;
  startDate: Timestamp | null;
  status: string | null;
  stripeApplicationFeeId: string | null;
  trainerId: string | null;
  updatedAt: Timestamp | null;
}

export interface VwLegacyPayment {
  clientSessionId: string | null;
  contributionAmount: number | null;
  createdAt: Timestamp | null;
  id: string | null;
  paidAmount: number | null;
  paidDate: Timestamp | null;
  paymentMethod: string | null;
  paymentType: string | null;
  planId: string | null;
  sessionPackId: string | null;
  status: string | null;
  stripeCharge: string | null;
  stripeRefund: string | null;
  trainerId: string | null;
  updatedAt: Timestamp | null;
}

export interface VwLegacyPlan {
  amount: number | null;
  clientId: string | null;
  currency: string | null;
  endDate: Timestamp | null;
  frequency: number | null;
  id: string | null;
  lastPaymentDate: Timestamp | null;
  name: string | null;
  nextPaymentDate: Timestamp | null;
  planPauses: Json | null;
  planPayments: Json | null;
  sessionSeriesIds: Json | null;
  startDate: Timestamp | null;
  status: string | null;
  trainerId: string | null;
}

export interface VwLegacyPlanPayment {
  amount: number | null;
  currency: string | null;
  date: Timestamp | null;
  id: string | null;
  outstandingAmount: number | null;
  planId: string | null;
  status: string | null;
}

export interface VwLegacySession {
  address: string | null;
  bookableOnline: boolean | null;
  bookedOnline: boolean | null;
  bookingPaymentType: string | null;
  bufferMinutesAfter: number | null;
  bufferMinutesBefore: number | null;
  canClientsCancel: boolean | null;
  clientReminder1: Json | null;
  clientReminder2: Json | null;
  clientSessions: Json | null;
  date: string | null;
  description: string | null;
  geo: Json | null;
  googlePlaceId: string | null;
  id: string | null;
  invitations: Json | null;
  length: number | null;
  location: string | null;
  maximumAttendance: number | null;
  notes: Json | null;
  serviceId: string | null;
  serviceProviderReminder1: Json | null;
  serviceProviderReminder2: Json | null;
  sessionSeriesId: string | null;
  timezone: string | null;
}

export interface VwLegacySession2 {
  address: string | null;
  bookableOnline: boolean | null;
  bookedOnline: boolean | null;
  bookingPaymentType: string | null;
  bookingQuestion: string | null;
  bookingQuestionState: string | null;
  bufferMinutesAfter: number | null;
  bufferMinutesBefore: number | null;
  cancellationAdvanceNoticeDuration: string | null;
  canClientsCancel: boolean | null;
  clientReminder1: Json | null;
  clientReminder2: Json | null;
  clientSessions: Json | null;
  currency: string | null;
  date: string | null;
  description: string | null;
  geo: Json | null;
  googlePlaceId: string | null;
  id: string | null;
  invitations: Json | null;
  length: number | null;
  location: string | null;
  maximumAttendance: number | null;
  name: string | null;
  notes: Json | null;
  price: string | null;
  requestClientAddressOnline: string | null;
  serviceId: string | null;
  serviceProviderReminder1: Json | null;
  serviceProviderReminder2: Json | null;
  sessionSeriesId: string | null;
  startTime: Timestamp | null;
  timezone: string | null;
  type: string | null;
}

export interface VwLegacySessionPack {
  amount: number | null;
  clientId: string | null;
  createdAt: Timestamp | null;
  id: string | null;
  name: string | null;
  paymentMethod: string | null;
  paymentStatus: string | null;
  sessionsRemaining: number | null;
  sessionsTotal: number | null;
  stripeCharge: string | null;
  stripeRefund: string | null;
  trainerId: string | null;
}

export interface VwLegacySessionSeries {
  avatarName: string | null;
  createdAt: Timestamp | null;
  currency: string | null;
  endDate: string | null;
  id: string | null;
  imageURL: string | null;
  location: string | null;
  price: number | null;
  reminderHours: number | null;
  repeatsEvery: number | null;
  sessionColor: string | null;
  sessionLength: number | null;
  sessionName: string | null;
  sessions: Json | null;
  sessionType: string | null;
  startDate: string | null;
  timezone: string | null;
  trainerId: string | null;
}

export interface VwLegacySessionSeries2 {
  avatarName: string | null;
  createdAt: Timestamp | null;
  currency: string | null;
  endDate: string | null;
  id: string | null;
  imageURL: string | null;
  location: string | null;
  price: number | null;
  reminderHours: number | null;
  repeatsEvery: number | null;
  sessionColor: string | null;
  sessionLength: number | null;
  sessionName: string | null;
  sessions: Json | null;
  sessionType: string | null;
  startDate: string | null;
  timezone: string | null;
  trainerId: string | null;
}

export interface VwLegacyTrainer {
  business_name: string | null;
  country: string | null;
  created_at: Timestamp | null;
  default_client_appointment_reminder_1: Json | null;
  default_client_appointment_reminder_2: Json | null;
  default_currency: string | null;
  default_service_provider_appointment_reminder_1: Json | null;
  default_service_provider_appointment_reminder_2: Json | null;
  device_id: string | null;
  email: string | null;
  first_card_payment_processed: Timestamp | null;
  first_name: string | null;
  id: string | null;
  last_name: string | null;
  locale: string | null;
  member_id: string | null;
  phone: string | null;
  sms_credit_balance: number | null;
  sms_credit_top_up_at: Timestamp | null;
  sms_credit_top_up_count: number | null;
  stripe_account_status: string | null;
  subscription: Json | null;
  terms_accepted: boolean | null;
  timezone: string | null;
}

export interface VwValidAccessToken {
  access_token: string | null;
  member_id: string | null;
  trainer_id: string | null;
}

export interface DB {
  access_token: AccessToken;
  access_token_type: AccessTokenType;
  account_subscription_status: AccountSubscriptionStatus;
  analytics_data: AnalyticsData;
  app_notification: AppNotification;
  app_store_pending_renewal_info: AppStorePendingRenewalInfo;
  app_store_server_notification: AppStoreServerNotification;
  app_store_transaction: AppStoreTransaction;
  apple_search_ads_attribution: AppleSearchAdsAttribution;
  availability: Availability;
  balance_transactions: BalanceTransactions;
  booking_payment_type: BookingPaymentType;
  booking_question_state: BookingQuestionState;
  brand_color: BrandColor;
  busy_time: BusyTime;
  client: Client;
  client_appointment_reminder_type: ClientAppointmentReminderType;
  client_login_request: ClientLoginRequest;
  client_note: ClientNote;
  client_payment_reminder: ClientPaymentReminder;
  client_session: ClientSession;
  client_session_state: ClientSessionState;
  client_status: ClientStatus;
  country: Country;
  credit_pack: CreditPack;
  currency: Currency;
  email_appointment_reminder: EmailAppointmentReminder;
  event_type: EventType;
  finance_item: FinanceItem;
  installation: Installation;
  logged_actions: LoggedActions;
  mail: Mail;
  mail_bounce: MailBounce;
  mail_bounce_type: MailBounceType;
  mail_click: MailClick;
  mail_open: MailOpen;
  "mandrill.event": MandrillEvent;
  message: Message;
  metrics: Metrics;
  mission: Mission;
  mission_type: MissionType;
  mrr: Mrr;
  payment: Payment;
  payment_credit_pack: PaymentCreditPack;
  payment_manual: PaymentManual;
  payment_method: PaymentMethod;
  payment_plan: PaymentPlan;
  payment_plan_acceptance: PaymentPlanAcceptance;
  payment_plan_charge: PaymentPlanCharge;
  payment_plan_pause: PaymentPlanPause;
  payment_plan_payment: PaymentPlanPayment;
  payment_plan_payment_status: PaymentPlanPaymentStatus;
  payment_plan_status: PaymentPlanStatus;
  payment_scheduled_stripe: PaymentScheduledStripe;
  payment_scheduled_stripe_attempt: PaymentScheduledStripeAttempt;
  payment_stats: PaymentStats;
  payment_status: PaymentStatus;
  payment_stripe: PaymentStripe;
  payment_subscription: PaymentSubscription;
  pg_stat_statements: PgStatStatements;
  pg_stat_statements_info: PgStatStatementsInfo;
  product: Product;
  request_client_address_online_type: RequestClientAddressOnlineType;
  reward: Reward;
  reward_type: RewardType;
  sale: Sale;
  sale_credit_pack: SaleCreditPack;
  sale_item: SaleItem;
  sale_payment_status: SalePaymentStatus;
  sale_product: SaleProduct;
  sale_service: SaleService;
  schema_history: SchemaHistory;
  schema_migrations: SchemaMigrations;
  service: Service;
  service_provider_appointment_reminder_type: ServiceProviderAppointmentReminderType;
  session: Session;
  session_icon: SessionIcon;
  session_series: SessionSeries;
  sms: Sms;
  sms_balance: SmsBalance;
  sms_credit: SmsCredit;
  sms_credit_checkout_session: SmsCreditCheckoutSession;
  sms_credit_source: SmsCreditSource;
  stripe_balance: StripeBalance;
  stripe_charge: StripeCharge;
  stripe_payment_intent: StripePaymentIntent;
  stripe_resource: StripeResource;
  "stripe.account": StripeAccount;
  "stripe.bank_account": StripeBankAccount;
  "stripe.checkout_session": StripeCheckoutSession;
  "stripe.customer": StripeCustomer;
  "stripe.event": StripeEvent;
  "stripe.invoice": StripeInvoice;
  "stripe.payment_method": StripePaymentMethod;
  "stripe.payout": StripePayout;
  "stripe.subscription": StripeSubscription;
  subscription: Subscription;
  subscription_frequency: SubscriptionFrequency;
  subscription_pause: SubscriptionPause;
  subscription_period: SubscriptionPeriod;
  subscription_update: SubscriptionUpdate;
  supported_country_currency: SupportedCountryCurrency;
  survey: Survey;
  tableslist: Tableslist;
  task_queue: TaskQueue;
  trainer: Trainer;
  trial: Trial;
  user_: User;
  user_type: UserType;
  vw_first_card_payments: VwFirstCardPayments;
  vw_legacy_app_notification: VwLegacyAppNotification;
  vw_legacy_client: VwLegacyClient;
  vw_legacy_client_session: VwLegacyClientSession;
  vw_legacy_finance_item: VwLegacyFinanceItem;
  vw_legacy_payment: VwLegacyPayment;
  vw_legacy_plan: VwLegacyPlan;
  vw_legacy_plan_payment: VwLegacyPlanPayment;
  vw_legacy_session: VwLegacySession;
  vw_legacy_session_2: VwLegacySession2;
  vw_legacy_session_pack: VwLegacySessionPack;
  vw_legacy_session_series: VwLegacySessionSeries;
  vw_legacy_session_series_2: VwLegacySessionSeries2;
  vw_legacy_trainer: VwLegacyTrainer;
  vw_valid_access_token: VwValidAccessToken;
}
