export type Currency = Readonly<{
  id: number
  alphaCode: string
  name: string
}>

// ISO 4217 currency list with numeric identifiers provided by user.
export const currencies: ReadonlyArray<Currency> = [
  { id: 8, alphaCode: 'ALL', name: 'Lek' },
  { id: 12, alphaCode: 'DZD', name: 'Algerian Dinar' },
  { id: 32, alphaCode: 'ARS', name: 'Argentine Peso' },
  { id: 36, alphaCode: 'AUD', name: 'Australian Dollar' },
  { id: 44, alphaCode: 'BSD', name: 'Bahamian Dollar' },
  { id: 48, alphaCode: 'BHD', name: 'Bahraini Dinar' },
  { id: 50, alphaCode: 'BDT', name: 'Taka' },
  { id: 51, alphaCode: 'AMD', name: 'Armenian Dram' },
  { id: 52, alphaCode: 'BBD', name: 'Barbados Dollar' },
  { id: 60, alphaCode: 'BMD', name: 'Bermudian Dollar' },
  { id: 64, alphaCode: 'BTN', name: 'Ngultrum' },
  { id: 68, alphaCode: 'BOB', name: 'Boliviano' },
  { id: 72, alphaCode: 'BWP', name: 'Pula' },
  { id: 84, alphaCode: 'BZD', name: 'Belize Dollar' },
  { id: 90, alphaCode: 'SBD', name: 'Solomon Islands Dollar' },
  { id: 96, alphaCode: 'BND', name: 'Brunei Dollar' },
  { id: 104, alphaCode: 'MMK', name: 'Kyat' },
  { id: 108, alphaCode: 'BIF', name: 'Burundi Franc' },
  { id: 116, alphaCode: 'KHR', name: 'Riel' },
  { id: 124, alphaCode: 'CAD', name: 'Canadian Dollar' },
  { id: 132, alphaCode: 'CVE', name: 'Cabo Verde Escudo' },
  { id: 136, alphaCode: 'KYD', name: 'Cayman Islands Dollar' },
  { id: 144, alphaCode: 'LKR', name: 'Sri Lanka Rupee' },
  { id: 152, alphaCode: 'CLP', name: 'Chilean Peso' },
  { id: 156, alphaCode: 'CNY', name: 'Yuan Renminbi' },
  { id: 170, alphaCode: 'COP', name: 'Colombian Peso' },
  { id: 174, alphaCode: 'KMF', name: 'Comorian Franc ' },
  { id: 188, alphaCode: 'CRC', name: 'Costa Rican Colon' },
  { id: 191, alphaCode: 'HRK', name: 'Kuna' },
  { id: 192, alphaCode: 'CUP', name: 'Cuban Peso' },
  { id: 203, alphaCode: 'CZK', name: 'Czech Koruna' },
  { id: 208, alphaCode: 'DKK', name: 'Danish Krone' },
  { id: 214, alphaCode: 'DOP', name: 'Dominican Peso' },
  { id: 222, alphaCode: 'SVC', name: 'El Salvador Colon' },
  { id: 230, alphaCode: 'ETB', name: 'Ethiopian Birr' },
  { id: 232, alphaCode: 'ERN', name: 'Nakfa' },
  { id: 238, alphaCode: 'FKP', name: 'Falkland Islands Pound' },
  { id: 242, alphaCode: 'FJD', name: 'Fiji Dollar' },
  { id: 262, alphaCode: 'DJF', name: 'Djibouti Franc' },
  { id: 270, alphaCode: 'GMD', name: 'Dalasi' },
  { id: 292, alphaCode: 'GIP', name: 'Gibraltar Pound' },
  { id: 320, alphaCode: 'GTQ', name: 'Quetzal' },
  { id: 324, alphaCode: 'GNF', name: 'Guinean Franc' },
  { id: 328, alphaCode: 'GYD', name: 'Guyana Dollar' },
  { id: 332, alphaCode: 'HTG', name: 'Gourde' },
  { id: 340, alphaCode: 'HNL', name: 'Lempira' },
  { id: 344, alphaCode: 'HKD', name: 'Hong Kong Dollar' },
  { id: 348, alphaCode: 'HUF', name: 'Forint' },
  { id: 352, alphaCode: 'ISK', name: 'Iceland Krona' },
  { id: 356, alphaCode: 'INR', name: 'Indian Rupee' },
  { id: 360, alphaCode: 'IDR', name: 'Rupiah' },
  { id: 364, alphaCode: 'IRR', name: 'Iranian Rial' },
  { id: 368, alphaCode: 'IQD', name: 'Iraqi Dinar' },
  { id: 376, alphaCode: 'ILS', name: 'New Israeli Sheqel' },
  { id: 388, alphaCode: 'JMD', name: 'Jamaican Dollar' },
  { id: 392, alphaCode: 'JPY', name: 'Yen' },
  { id: 398, alphaCode: 'KZT', name: 'Tenge' },
  { id: 400, alphaCode: 'JOD', name: 'Jordanian Dinar' },
  { id: 404, alphaCode: 'KES', name: 'Kenyan Shilling' },
  { id: 408, alphaCode: 'KPW', name: 'North Korean Won' },
  { id: 410, alphaCode: 'KRW', name: 'Won' },
  { id: 414, alphaCode: 'KWD', name: 'Kuwaiti Dinar' },
  { id: 417, alphaCode: 'KGS', name: 'Som' },
  { id: 418, alphaCode: 'LAK', name: 'Lao Kip' },
  { id: 422, alphaCode: 'LBP', name: 'Lebanese Pound' },
  { id: 426, alphaCode: 'LSL', name: 'Loti' },
  { id: 430, alphaCode: 'LRD', name: 'Liberian Dollar' },
  { id: 434, alphaCode: 'LYD', name: 'Libyan Dinar' },
  { id: 446, alphaCode: 'MOP', name: 'Pataca' },
  { id: 454, alphaCode: 'MWK', name: 'Malawi Kwacha' },
  { id: 458, alphaCode: 'MYR', name: 'Malaysian Ringgit' },
  { id: 462, alphaCode: 'MVR', name: 'Rufiyaa' },
  { id: 480, alphaCode: 'MUR', name: 'Mauritius Rupee' },
  { id: 484, alphaCode: 'MXN', name: 'Mexican Peso' },
  { id: 496, alphaCode: 'MNT', name: 'Tugrik' },
  { id: 498, alphaCode: 'MDL', name: 'Moldovan Leu' },
  { id: 504, alphaCode: 'MAD', name: 'Moroccan Dirham' },
  { id: 512, alphaCode: 'OMR', name: 'Rial Omani' },
  { id: 516, alphaCode: 'NAD', name: 'Namibia Dollar' },
  { id: 524, alphaCode: 'NPR', name: 'Nepalese Rupee' },
  { id: 532, alphaCode: 'ANG', name: 'Netherlands Antillean Guilder' },
  { id: 533, alphaCode: 'AWG', name: 'Aruban Florin' },
  { id: 548, alphaCode: 'VUV', name: 'Vatu' },
  { id: 554, alphaCode: 'NZD', name: 'New Zealand Dollar' },
  { id: 558, alphaCode: 'NIO', name: 'Cordoba Oro' },
  { id: 566, alphaCode: 'NGN', name: 'Naira' },
  { id: 578, alphaCode: 'NOK', name: 'Norwegian Krone' },
  { id: 586, alphaCode: 'PKR', name: 'Pakistan Rupee' },
  { id: 590, alphaCode: 'PAB', name: 'Balboa' },
  { id: 598, alphaCode: 'PGK', name: 'Kina' },
  { id: 600, alphaCode: 'PYG', name: 'Guarani' },
  { id: 604, alphaCode: 'PEN', name: 'Sol' },
  { id: 608, alphaCode: 'PHP', name: 'Philippine Peso' },
  { id: 634, alphaCode: 'QAR', name: 'Qatari Rial' },
  { id: 643, alphaCode: 'RUB', name: 'Russian Ruble' },
  { id: 646, alphaCode: 'RWF', name: 'Rwanda Franc' },
  { id: 654, alphaCode: 'SHP', name: 'Saint Helena Pound' },
  { id: 682, alphaCode: 'SAR', name: 'Saudi Riyal' },
  { id: 690, alphaCode: 'SCR', name: 'Seychelles Rupee' },
  { id: 694, alphaCode: 'SLL', name: 'Leone' },
  { id: 702, alphaCode: 'SGD', name: 'Singapore Dollar' },
  { id: 704, alphaCode: 'VND', name: 'Dong' },
  { id: 706, alphaCode: 'SOS', name: 'Somali Shilling' },
  { id: 710, alphaCode: 'ZAR', name: 'Rand' },
  { id: 728, alphaCode: 'SSP', name: 'South Sudanese Pound' },
  { id: 748, alphaCode: 'SZL', name: 'Lilangeni' },
  { id: 752, alphaCode: 'SEK', name: 'Swedish Krona' },
  { id: 756, alphaCode: 'CHF', name: 'Swiss Franc' },
  { id: 760, alphaCode: 'SYP', name: 'Syrian Pound' },
  { id: 764, alphaCode: 'THB', name: 'Baht' },
  { id: 776, alphaCode: 'TOP', name: 'Pa’anga' },
  { id: 780, alphaCode: 'TTD', name: 'Trinidad and Tobago Dollar' },
  { id: 784, alphaCode: 'AED', name: 'UAE Dirham' },
  { id: 788, alphaCode: 'TND', name: 'Tunisian Dinar' },
  { id: 800, alphaCode: 'UGX', name: 'Uganda Shilling' },
  { id: 807, alphaCode: 'MKD', name: 'Denar' },
  { id: 818, alphaCode: 'EGP', name: 'Egyptian Pound' },
  { id: 826, alphaCode: 'GBP', name: 'Pound Sterling' },
  { id: 834, alphaCode: 'TZS', name: 'Tanzanian Shilling' },
  { id: 840, alphaCode: 'USD', name: 'US Dollar' },
  { id: 858, alphaCode: 'UYU', name: 'Peso Uruguayo' },
  { id: 860, alphaCode: 'UZS', name: 'Uzbekistan Sum' },
  { id: 882, alphaCode: 'WST', name: 'Tala' },
  { id: 886, alphaCode: 'YER', name: 'Yemeni Rial' },
  { id: 901, alphaCode: 'TWD', name: 'New Taiwan Dollar' },
  { id: 927, alphaCode: 'UYW', name: 'Unidad Previsional' },
  { id: 928, alphaCode: 'VES', name: 'Bolívar Soberano' },
  { id: 929, alphaCode: 'MRU', name: 'Ouguiya' },
  { id: 930, alphaCode: 'STN', name: 'Dobra' },
  { id: 931, alphaCode: 'CUC', name: 'Peso Convertible' },
  { id: 932, alphaCode: 'ZWL', name: 'Zimbabwe Dollar' },
  { id: 933, alphaCode: 'BYN', name: 'Belarusian Ruble' },
  { id: 934, alphaCode: 'TMT', name: 'Turkmenistan New Manat' },
  { id: 936, alphaCode: 'GHS', name: 'Ghana Cedi' },
  { id: 938, alphaCode: 'SDG', name: 'Sudanese Pound' },
  { id: 940, alphaCode: 'UYI', name: 'Uruguay Peso en Unidades Indexadas (UI)' },
  { id: 941, alphaCode: 'RSD', name: 'Serbian Dinar' },
  { id: 943, alphaCode: 'MZN', name: 'Mozambique Metical' },
  { id: 944, alphaCode: 'AZN', name: 'Azerbaijan Manat' },
  { id: 946, alphaCode: 'RON', name: 'Romanian Leu' },
  { id: 947, alphaCode: 'CHE', name: 'WIR Euro' },
  { id: 948, alphaCode: 'CHW', name: 'WIR Franc' },
  { id: 949, alphaCode: 'TRY', name: 'Turkish Lira' },
  { id: 950, alphaCode: 'XAF', name: 'CFA Franc BEAC' },
  { id: 951, alphaCode: 'XCD', name: 'East Caribbean Dollar' },
  { id: 952, alphaCode: 'XOF', name: 'CFA Franc BCEAO' },
  { id: 953, alphaCode: 'XPF', name: 'CFP Franc' },
  { id: 955, alphaCode: 'XBA', name: 'Bond Markets Unit European Composite Unit (EURCO)' },
  { id: 956, alphaCode: 'XBB', name: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)' },
  { id: 957, alphaCode: 'XBC', name: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)' },
  { id: 958, alphaCode: 'XBD', name: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)' },
  { id: 959, alphaCode: 'XAU', name: 'Gold' },
  { id: 960, alphaCode: 'XDR', name: 'SDR (Special Drawing Right)' },
  { id: 961, alphaCode: 'XAG', name: 'Silver' },
  { id: 962, alphaCode: 'XPT', name: 'Platinum' },
  { id: 963, alphaCode: 'XTS', name: 'Codes specifically reserved for testing purposes' },
  { id: 964, alphaCode: 'XPD', name: 'Palladium' },
  { id: 965, alphaCode: 'XUA', name: 'ADB Unit of Account' },
  { id: 967, alphaCode: 'ZMW', name: 'Zambian Kwacha' },
  { id: 968, alphaCode: 'SRD', name: 'Surinam Dollar' },
  { id: 969, alphaCode: 'MGA', name: 'Malagasy Ariary' },
  { id: 970, alphaCode: 'COU', name: 'Unidad de Valor Real' },
  { id: 971, alphaCode: 'AFN', name: 'Afghani' },
  { id: 972, alphaCode: 'TJS', name: 'Somoni' },
  { id: 973, alphaCode: 'AOA', name: 'Kwanza' },
  { id: 975, alphaCode: 'BGN', name: 'Bulgarian Lev' },
  { id: 976, alphaCode: 'CDF', name: 'Congolese Franc' },
  { id: 977, alphaCode: 'BAM', name: 'Convertible Mark' },
  { id: 978, alphaCode: 'EUR', name: 'Euro' },
  { id: 979, alphaCode: 'MXV', name: 'Mexican Unidad de Inversion (UDI)' },
  { id: 980, alphaCode: 'UAH', name: 'Hryvnia' },
  { id: 981, alphaCode: 'GEL', name: 'Lari' },
  { id: 984, alphaCode: 'BOV', name: 'Mvdol' },
  { id: 985, alphaCode: 'PLN', name: 'Zloty' },
  { id: 986, alphaCode: 'BRL', name: 'Brazilian Real' },
  { id: 990, alphaCode: 'CLF', name: 'Unidad de Fomento' },
  { id: 994, alphaCode: 'XSU', name: 'Sucre' },
  { id: 997, alphaCode: 'USN', name: 'US Dollar (Next day)' },
  { id: 999, alphaCode: 'XXX', name: 'The codes assigned for transactions where no currency is involved' },
]
